# ---------------------------------------
# site setting
# ---------------------------------------
title: L.E.T
description: Learned! Experience! Think!

author:
   name: gloria
   contact:
      email: pureainu@gmail.com
      github: https://github.com/gloriaJun/

permalink: pretty

# Where are tags and categories displayed
tag_page: '/tags/'
category_page: '/categories/'


# ---------------------------------------
# paging
# ---------------------------------------
# 한 페이지에 출력할 글의 갯수
paginate: 10

# ---------------------------------------
# markdown
# ---------------------------------------
markdown: kramdown
krandown:
  input: GFM
  highlighter: rouge
  
# ---------------------------------------
# build setting
# ---------------------------------------
exclude: 
   - README.md
   - LICENSE
   - bower.json
   - Gemfile.lock
   - Gemfile

gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-sitemap
